# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-09 18:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogdata', '0009_auto_20160909_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postimage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blogdata.Image'),
        ),
    ]
