# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-09 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogdata', '0012_delete_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postimage',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
